---
- hosts: localhost
  connection: local
  tasks:
    - name: Terminate Instances
      ec2_instance_info:
        region: us-east-1
        filters:
          "tag:Name": MyTargetEc2Instance
        # instance_ids: i-01a1e47b2d10bf392
      register: ec2_info
 
    - name: displaying output
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"
 
    - name: terminate
      ec2:
        instance_ids: "{{item.instance_id}}"
        region: us-east-1
        state: absent
        wait: yes
      with_items: "{{ec2_info.instances}}"

